spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://120.24.234.60:3306/ems?autoReconnect=true&failOverReadOnly=false&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 'jz123$1A'
    hikari:
      idle-timeout: 10000
  application:
    name: feign-consumer
  data:
    mongodb:
      uri: mongodb://admin:jz123$1@120.24.234.60:27017/ems
  rabbitmq:
    host: 120.24.234.128
    port: 5672
    username: admin
    password: 'jz123$1'
  redis:
    host: 120.24.234.128
    port: 6379
    password: 'jz123$1'
    timeout: 100000
    database: 1
    lettuce:
      pool:
        max-active: 1000
        max-idle: 300
        min-idle: 0