spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/ems?autoReconnect=true&failOverReadOnly=false&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      idle-timeout: 10000
  data:
    mongodb:
      uri: mongodb://ems:!qaz2wsx@47.106.229.3:27018/ems_test
  rabbitmq:
    host: 47.106.229.3
    port: 5672
    username: ems
    password: '!qaz2wsx'
  redis:
    host: 47.106.229.3
    port: 6379
    password: '!qaz2wsx'
    timeout: 100000
    database: 1
    lettuce:
      pool:
        max-active: 1000
        max-idle: 300
        min-idle: 0